// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7wcZHb91tVc8Fcdom8IYX0xvldvCPFV8',
    appId: '1:245432851407:web:14e2c50be945fa97fe50ba',
    messagingSenderId: '245432851407',
    projectId: 'homy-8fb90',
    authDomain: 'homy-8fb90.firebaseapp.com',
    storageBucket: 'homy-8fb90.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC71FE4Kngz9a8VEISWH6A-rE3hVu0A9eQ',
    appId: '1:245432851407:android:a8959ce96915f495fe50ba',
    messagingSenderId: '245432851407',
    projectId: 'homy-8fb90',
    storageBucket: 'homy-8fb90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxgTKJ78STCj8xYH73aXlA5UrekjA-NqQ',
    appId: '1:245432851407:ios:3b46310e73351527fe50ba',
    messagingSenderId: '245432851407',
    projectId: 'homy-8fb90',
    storageBucket: 'homy-8fb90.firebasestorage.app',
    iosBundleId: 'com.example.homy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxgTKJ78STCj8xYH73aXlA5UrekjA-NqQ',
    appId: '1:245432851407:ios:3b46310e73351527fe50ba',
    messagingSenderId: '245432851407',
    projectId: 'homy-8fb90',
    storageBucket: 'homy-8fb90.firebasestorage.app',
    iosBundleId: 'com.example.homy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7wcZHb91tVc8Fcdom8IYX0xvldvCPFV8',
    appId: '1:245432851407:web:88fcba1295178f59fe50ba',
    messagingSenderId: '245432851407',
    projectId: 'homy-8fb90',
    authDomain: 'homy-8fb90.firebaseapp.com',
    storageBucket: 'homy-8fb90.firebasestorage.app',
  );

}